### ISSUE TITLE
AutoDL部署，视频无法加载报错

### ISSUE THREAD

**Issue by jakciehoo** [lipku/metahuman-stream#106]
我按照群主的autoDL部署教程部署的。端口也开放了。
![image](https://github.com/lipku/metahuman-stream/assets/10362781/3160b3ad-9577-4c0c-b7e1-27ca6f4628ff)
但是运行报错，视频一直加载不出来
![image](https://github.com/lipku/metahuman-stream/assets/10362781/10b02557-e299-4ff2-9967-4c68c49febf5)
昨天到今天都尝试去解决，看源码，但是后端这块不太懂，所以还是找不到问题所在，所以问问这个错误原因什么如何修复。求大佬解答

**Comment by Kevin746p** [comment]
请问一下是怎么解决的

**Comment by SSSh1wein4n** [comment]
你好，部署教程在哪里？
