### ISSUE TITLE
websocket连接问题

### ISSUE THREAD

**Issue by plore77** [lipku/metahuman-stream#107]
想请问一下日志显示websocket已连接，rtcpush.html可以看到视频，但是一发送文字就报错websocket断开是怎么回事，用的模型是musetalk和gptsovits

![微信图片_20240606180508](https://github.com/lipku/metahuman-stream/assets/138968468/e9e260a9-f53e-4118-ad70-a95162a0f06f)

![微信图片_20240606180517](https://github.com/lipku/metahuman-stream/assets/138968468/85558dcc-0480-4b7e-a9d4-a6ebcbfa1d16)
matcher.py和flask_socket均已做修改。防火墙是关闭状态

![image](https://github.com/lipku/metahuman-stream/assets/138968468/d20fb522-5a91-4738-a52a-3afb9dc653cb)

**Comment by yangling-happy** [comment]
你好问问怎么解决的，遇到了同样的情况
