### ISSUE TITLE
使用AUTODL部署的时候无法展示视频，部署了阿里SRS服务，也无法展示视频

### ISSUE THREAD

**Issue by Kevin746p** [lipku/metahuman-stream#108]
rtcpushapi.html
![image](https://github.com/lipku/metahuman-stream/assets/56906392/1e571d22-a0d7-491e-aa86-1953eaf73b06)
![image](https://github.com/lipku/metahuman-stream/assets/56906392/c0623e67-c40f-413b-9292-f3d88eb7e2f8)

**Comment by yehx1** [comment]
请问解决了吗？
