### ISSUE TITLE
MuseTalk 运行的时候 是不是目前不支持对话呀 运行的命令是 python app.py --model musetalk --transport webrtc

### ISSUE THREAD

**Issue by anstonjie** [lipku/metahuman-stream#116]
然后打开 http://127.0.0.1:8010/rtcpushchat.html
的时候链接不上服务器 无法进行相关的操作没有视频显示 也不能进行对话

运行http://127.0.0.1:8010/webrtcapi.html 这个是可以按照你提示什么 他读什么 但是不能对话

**Comment by musexiaoluo** [comment]
你是在aududl 上运行的吗

**Comment by Qiang-Lin** [comment]
项目里llm那块代码功能没改完，需要自己把前端请求改成chat，然后app.py 里面有llm_response函数，改成自己习惯用的大模型接口

**Comment by anstonjie** [comment]
谢谢 我试试
