### ISSUE TITLE
实现NVIDIA硬件加速编码

### ISSUE THREAD

**Issue by weiyiferonia** [lipku/metahuman-stream#117]
请问如何实现使用NVIDIA硬件加速编码推流提高实时性？

**Comment by ysc3839** [comment]
个人测试似乎不会带来太大性能提升
i7-6700 RTX 2080 软件编码 22fps 硬件编码24fps，分辨率 450x450

**Comment by weiyiferonia** [comment]
> 个人测试似乎不会带来太大性能提升 i7-6700 RTX 2080 软件编码 22fps 硬件编码24fps，分辨率 450x450
可以分享下你硬编码的实现方式吗？

**Comment by weiyiferonia** [comment]
> 个人测试似乎不会带来太大性能提升 i7-6700 RTX 2080 软件编码 22fps 硬件编码24fps，分辨率 450x450
软编码需要先将图像从显存拷贝到内存，再结合full image软编码，硬编码将full image可以预拷贝提前放显存，那模型推理出来后的图像直接贴回full image，再通过硬件加速编码，这样的差距还是挺明显的，尤其是在高码率的2K分辨率的视频上。

**Comment by lipku** [comment]
显存占用太大，fullimg耗的内存太多，现在cpu编码能力还行

**Comment by ysc3839** [comment]
@weiyiferonia 是用 C++ 调用 Python 和 NVENC 实现的。
如果是把推理结果合成到一个更大的画面再编码，不知道 Python 做 GPU 画面合成是否方便。

**Comment by weiyiferonia** [comment]
> 显存占用太大，fullimg耗的内存太多，现在cpu编码能力还行

如果是几秒的视频循环播放的话，显存占用是可控的，也不影响内存。如果是长视频推理，那就要考虑动态加载，大部分压力转到在IO上了。我试过高分辨率的编码推流，还是会影响实时，并发也难上去。

**Comment by weiyiferonia** [comment]
> @weiyiferonia 是用 C++ 调用 Python 和 NVENC 实现的。 如果是把推理结果合成到一个更大的画面再编码，不知道 Python 做 GPU 画面合成是否方便。

GPU合成一个更大的画面挺方便的，我觉得难点在编码优化这一块上，方便加个联系方式交流下经验么？

**Comment by weiyiferonia** [comment]
> @weiyiferonia 直接在这里沟通吧。 我没有做特殊的编码优化，就是从 PyTorch 拿到 CUDA 显存指针后传给 NVENC 编码，似乎没什么难的。其他的优化方法我也不知道。

好的，谢谢
