### ISSUE TITLE
musetalk模式下背景替换后不生效

### ISSUE THREAD

**Issue by ShelikeSnow** [lipku/metahuman-stream#121]
python app.py --listenport 6006 --transport webrtc --avatar_id avator_2 --model musetalk --fps 25 --batch_size 8 --customvideo --customvideo_img customvideo --customvideo_imgnum 23

依然是播放avator_1下full_imgs的照片

**Comment by TigerHH6866** [comment]
musetalk貌似不能换背景

**Comment by ShelikeSnow** [comment]
> musetalk貌似不能换背景

我自己改了 这个是静止模式下指定不生效。问题发错了
