### ISSUE TITLE
亲爱的 PyGui 展示

### ISSUE THREAD

**Issue by bandit-masked** [lipku/metahuman-stream#14]
你好 我认为 metahuman-stream 可能会使 对 GitHub 上 Dear PyGui 展示的重要补充。 https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase 您是否愿意创建一个简短的 GIF（小于 8 Mb），我们可以将其包含在展示中？ 感谢您的考虑
---

Hi,

I think that metahuman-stream might make a 
great addition to the Dear PyGui showcase on GitHub. 

https://github.com/hoffstadt/DearPyGui/wiki/Dear-PyGui-Showcase

Would you be willing to create a short GIF (less than 8 Mb) that we could include in the showcase?

Thanks for your consideration

**Comment by lipku** [comment]
好的，怎么发给你

**Comment by bandit-masked** [comment]
谢谢！ 这里有两个选项。 1. 将 GIF 文件上传到您自己的 GitHub，并在下面发布指向 GIF 的链接作为反应。 2. 在此处创建一个问题：https://github.com/DataExplorerUser/dpg_resources/issues/new，然后在那里上传 GIF 文件。 再次感谢！

Thank you very much! Here are two options.

1. Upload the GIF file to your own GitHub and post a link to the GIF as a reaction below.

2. Create an issue here: https://github.com/DataExplorerUser/dpg_resources/issues/new, and upload the GIF-file there.

Thanks again!
