### ISSUE TITLE
AutoDL 环境 RtcPush 连接失败

### ISSUE THREAD

**Issue by yni9ht** [lipku/metahuman-stream#141]
### 环境信息
- AutoDL（A800）： 运行本项目
- 腾讯云服务器：运行 SRS 推流服务（已开放 TCP：1985 UDP：8000)
- 推流协议：rtcpush
- 推流地址：http://{腾讯云服务器IP}:1985/rtc/v1/whip/?app=live&stream=livestream

### 描述
我在本地环境用同样协议和推流地址是可以正常推流并拉流展示的，但是在 AutoDL 里的示例启动后就报 RTC 连接建立失败。

### 报错信息
```
start websocket server
Connection state is connecting
start inference
Connection state is failed
Connection state is closed
```

**Comment by yni9ht** [comment]
SRS 后台没有报错信息

**Comment by yni9ht** [comment]
刚在 AutoDL 上测试其他分区和GPU的实例后没问题了，在 L20 专区的实例上测试可以正常推流。

**Comment by chj113** [comment]
貌似autodl部分区域的服务器无法正常使用

**Comment by yni9ht** [comment]
> 貌似autodl部分区域的服务器无法正常使用

是的，部分可用区的网络有一些差异，可能会导致无法使用类似 WebRTC 等服务

**Comment by zhaofeng3012** [comment]
> > 貌似autodl部分区域的服务器无法正常使用
> 
> 是的，部分可用区的网络有一些差异，可能会导致无法使用类似 WebRTC 等服务

您好，咨询一下是要在另一台有公网IP的云服务器上启动的srs吗？
export CANDIDATE='<服务器外网ip>' 这里的服务器外网ip是指启动srs服务的机器本身的公网ip？还是指运行数字人生成的GPU服务器的公网ip？

**Comment by yni9ht** [comment]
> > > 貌似autodl部分区域的服务器无法正常使用
> > 
> > 
> > 是的，部分可用区的网络有一些差异，可能会导致无法使用类似 WebRTC 等服务
> 
> 您好，咨询一下是要在另一台有公网IP的云服务器上启动的srs吗？ export CANDIDATE='<服务器外网ip>' 这里的服务器外网ip是指启动srs服务的机器本身的公网ip？还是指运行数字人生成的GPU服务器的公网ip？

SRS 服务对应的服务器公网IP
