### ISSUE TITLE
延时问题

### ISSUE THREAD

**Issue by ThetaRgo** [lipku/metahuman-stream#15]
项目正常跑通，4090上延时还是很大，而且跑的越久延时越大，一开始大概延时20秒往上，几分钟后延时会达到几分钟，请问这是什么原因？

**Comment by lipku** [comment]
日志打印的fps是多少

**Comment by ThetaRgo** [comment]
fps可以了，之前是docker跑的，可能是环境因素，本地装后没问题了。

**Comment by hepburnalex** [comment]
> fps可以了，之前是docker跑的，可能是环境因素，本地装后没问题了。

我也遇到了同样的问题，我是在win11上用docker跑的，也是4090，请问你是怎么解决的？
