### ISSUE TITLE
python app.py --transport webrtc: [error] coords.pkl not found

### ISSUE THREAD

**Issue by Jacoo-ai** [lipku/metahuman-stream#160]
When I run **python app.py --transport webrtc**, there is an error:

FileNotFoundError: [Errno 2] No such file or directory: './data/avatars/avator_1/coords.pkl'
<img width="558" alt="ERROR" src="https://github.com/user-attachments/assets/86f087dc-b9d4-4388-876b-15bb741faa55">

Could you please check it?

**Comment by lipku** [comment]
Read wav2lip part in readme, download wav2lip avatar files

**Comment by Jacoo-ai** [comment]
Problem solved! Thank you very much :)
