### ISSUE TITLE
使用musetalk 的时候默认的edgetts 说话的音量特别小

### ISSUE THREAD

**Issue by mmlingyu** [lipku/metahuman-stream#169]
首先不是设备问题
调节过edgetts 音量设置
 def txt_to_audio(self,msg):
        voicename = "zh-CN-YunxiaNeural"
        text = msg
        t = time.time()
        volume = '+100%'
        asyncio.new_event_loop().run_until_complete(self.__main(voicename,text,volume))
        print(f'-------edge tts time:{time.time()-t:.4f}s')

效果一样 请问哪里的问题，srs doocker里面的配置么

**Comment by BO-DI** [comment]
https://github.com/user-attachments/assets/d2379488-6867-4700-b313-33efa5cda210
我得大概是这样
