### ISSUE TITLE
换自己训练的模型运行就报错，大佬帮看看，感谢！

### ISSUE THREAD

**Issue by stevin-dong** [lipku/metahuman-stream#17]
换自己的训练模型时，声音我是用的Hubert， 启动app.py报错，大佬帮看看，感谢！
    trainer = Trainer('ngp', opt, model, device=device, workspace=opt.workspace, criterion=criterion, fp16=opt.fp16, metrics=metrics, use_checkpoint=opt.ckpt)
  File "/root/nerf/nerf_triplane/utils.py", line 724, in __init__
    self.load_checkpoint(self.use_checkpoint)
  File "/root/nerf/nerf_triplane/utils.py", line 1824, in load_checkpoint
    missing_keys, unexpected_keys = self.model.load_state_dict(checkpoint_dict['model'], strict=False)
  File "/root/miniconda3/envs/er/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
        size mismatch for individual_codes: copying a param with shape torch.Size([12000, 4]) from checkpoint, the shape in current model is torch.Size([10000, 4]).
        size mismatch for individual_codes_torso: copying a param with shape torch.Size([12000, 8]) from checkpoint, the shape in current model is torch.Size([10000, 8]).

**Comment by lipku** [comment]
训练时的音频要用wav2vec

**Comment by stevin-dong** [comment]
> 训练时的音频要用wav2vec

我们一直用的hubert，感觉这个口型较好，这个没法修改吗？大佬

**Comment by stevin-dong** [comment]
> 训练时的音频要用wav2vec

训练时，换了wav2vec还是报以上同样的错误，我训练出来的模型是38.4M，我看作者大佬是的ngp_kf.pth文件大小是38M，哪里有问题呢

**Comment by lipku** [comment]
那可能是你用的float32训练的模型，把app.py里的opt.fp16 = True这行注释掉看看

**Comment by ThetaRgo** [comment]
一样的，用的hubert，大佬能支持下么？hubert口型好点。

**Comment by lipku** [comment]
只支持用wav2vec训练的模型

**Comment by xiao-keeplearning** [comment]
问下hubert是不支持流式么 @lipku

**Comment by lipku** [comment]
已经支持hubert了

**Comment by lianping1985** [comment]
> 已经支持hubert了
这个需要修改哪里吗？我用hubert训练的还是报错

**Comment by cacard** [comment]
@lianping1985 解决了吗？我是同样的错误。
