### ISSUE TITLE
编译raymarching.cu的时候出现错误：fatal error C1189: #error:  You need C++17 to compile  PyTorch

### ISSUE THREAD

**Issue by wxzz** [lipku/metahuman-stream#182]
C:\Users\WXZZ\Desktop\metahuman-stream-main>python app.py
Traceback (most recent call last):
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\ernerf\raymarching\raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\Lib\site-packages\torch\utils\cpp_extension.py", line 2100, in _run_ninja_build
    subprocess.run(
  File "D:\Anaconda3\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\app.py", line 332, in <module>
    from ernerf.nerf_triplane.network import NeRFNetwork
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\ernerf\nerf_triplane\network.py", line 6, in <module>
    from .renderer import NeRFRenderer
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\ernerf\nerf_triplane\renderer.py", line 10, in <module>
    from .. import raymarching
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\ernerf\raymarching\__init__.py", line 1, in <module>
    from .raymarching import *
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\ernerf\raymarching\raymarching.py", line 12, in <module>
    from .backend import _backend
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\ernerf\raymarching\backend.py", line 31, in <module>
    _backend = load(name='_raymarching_face',
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\Anaconda3\Lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\Anaconda3\Lib\site-packages\torch\utils\cpp_extension.py", line 2116, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_raymarching_face': [1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12
.6\bin\nvcc --generate-dependencies-with-compile --dependency-output raymarching.cuda.o.d -Xcudafe --diag_suppress=dll_i
nterface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppres
s=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompile
r /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4
267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=_raymarching_face -DT
ORCH_API_INCLUDE_EXTENSION_H -ID:\Anaconda3\Lib\site-packages\torch\include -ID:\Anaconda3\Lib\site-packages\torch\inclu
de\torch\csrc\api\include -ID:\Anaconda3\Lib\site-packages\torch\include\TH -ID:\Anaconda3\Lib\site-packages\torch\inclu
de\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include" -ID:\Anaconda3\Include -D_GLIBCXX_USE_CXX11_
ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_O
PERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 -std=c+
+17 -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_CONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c C:\Users
\WXZZ\Desktop\metahuman-stream-main\ernerf\raymarching\src\raymarching.cu -o raymarching.cuda.o
FAILED: raymarching.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\nvcc --generate-dependencies-with-compile --dependency-outp
ut raymarching.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_i
nterface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_
has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190
 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcom
piler /MD -DTORCH_EXTENSION_NAME=_raymarching_face -DTORCH_API_INCLUDE_EXTENSION_H -ID:\Anaconda3\Lib\site-packages\torc
h\include -ID:\Anaconda3\Lib\site-packages\torch\include\torch\csrc\api\include -ID:\Anaconda3\Lib\site-packages\torch\i
nclude\TH -ID:\Anaconda3\Lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6
\include" -ID:\Anaconda3\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__
-D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=
compute_61 -gencode=arch=compute_61,code=sm_61 -std=c++17 -O3 -std=c++14 -U__CUDA_NO_HALF_OPERATORS__ -U__CUDA_NO_HALF_C
ONVERSIONS__ -U__CUDA_NO_HALF2_OPERATORS__ -c C:\Users\WXZZ\Desktop\metahuman-stream-main\ernerf\raymarching\src\raymarc
hing.cu -o raymarching.cuda.o
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_OPERATORS__”(用“/U__CUDA_NO_HALF_OPERATORS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF_CONVERSIONS__”(用“/U__CUDA_NO_HALF_CONVERSIONS__”)
cl: 命令行 warning D9025 :正在重写“/D__CUDA_NO_HALF2_OPERATORS__”(用“/U__CUDA_NO_HALF2_OPERATORS__”)
raymarching.cu
D:/Anaconda3/Lib/site-packages/torch/include\c10/util/C++17.h(27): fatal error C1189: #error:  You need C++17 to compile
 PyTorch
nvcc warning : incompatible redefinition for option 'std', the last value of this option was used
raymarching.cu
ninja: build stopped: subcommand failed.

备注：cuda 是12.6版本。
![QQ截图20240802161058](https://github.com/user-attachments/assets/56adb1ba-04de-4461-95f5-735d4d718ee6)

**Comment by wxzz** [comment]
应该是不支持windows吧。
![image](https://github.com/user-attachments/assets/db6ad769-04bd-4a16-be23-68b2657c72c8)

**Comment by charles4song** [comment]
更改成c++14了，还是报这个异常。

**Comment by charles4song** [comment]
> 更改成c++17了，还是报这个异常。Ubuntu22，g++ 11.4

好了。有2个c++14,需要都替换了

**Comment by wxzz** [comment]
> > 更改成c++17了，还是报这个异常。Ubuntu22，g++ 11.4
> 
> 好了。有2个c++14,需要都替换了

@charles4song 我应该怎么操作一下？

**Comment by charles4song** [comment]
> > > 更改成c++17了，还是报这个异常。Ubuntu22，g++ 11.4
> > 
> > 
> > 好了。有2个c++14,需要都替换了
> 
> @charles4song 我应该怎么操作一下？

搜索替换下。要不然容易疏忽

<img width="804" alt="联想截图_20240802233059" src="https://github.com/user-attachments/assets/d3b9a5f2-66db-496e-b7f9-2fabe2cb9a9a">

**Comment by wxzz** [comment]
> > > > 更改成c++17了，还是报这个异常。Ubuntu22，g++ 11.4
> > > 
> > > 
> > > 好了。有2个c++14,需要都替换了
> > 
> > 
> > @charles4song 我应该怎么操作一下？
> 
> 搜索替换下。要不然容易疏忽
> 
> <img alt="联想截图_20240802233059" width="804" src="https://private-user-images.githubusercontent.com/131432377/354646589-d3b9a5f2-66db-496e-b7f9-2fabe2cb9a9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MzcyODgsIm5iZiI6MTcyMjYzNjk4OCwicGF0aCI6Ii8xMzE0MzIzNzcvMzU0NjQ2NTg5LWQzYjlhNWYyLTY2ZGItNDk2ZS1iN2Y5LTJmYWJlMmNiOWE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQyMjE2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTFlMzJjZjc4ODVjMGJjNjNhOGNlMDM4N2NmMWMzYzcxMzlkMWJkYjQ1OTBmNjliODI2Njc5NTQ2ZTVhZDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UcL8bsCswCTxWNDw1BNNPb7q9C10Xpcx2QGe_myhqFM">

@charles4song 我用的windows也这样改吗？谢谢。

**Comment by wxzz** [comment]
@charles4song 已经解决，谢谢。应该是nvcc_flags变量-std=c++17这的问题。
