### ISSUE TITLE
Error: Cannot connect to host localhost:1985 ssl:default [远程计算机拒绝网络连接。请问windows下如何启动srs???

### ISSUE THREAD

**Issue by wxzz** [lipku/metahuman-stream#184]
Error: Cannot connect to host localhost:1985 ssl:default [远程计算机拒绝网络连接。]
Traceback (most recent call last):
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\app.py", line 429, in <module>
    run_server(web.AppRunner(appasync))
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\app.py", line 426, in run_server
    loop.run_until_complete(run(opt.push_url))
  File "D:\Anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\WXZZ\Desktop\metahuman-stream-main\app.py", line 184, in run
    await pc.setRemoteDescription(RTCSessionDescription(sdp=answer,type='answer'))
  File "D:\Anaconda3\Lib\site-packages\aiortc\rtcpeerconnection.py", line 829, in setRemoteDescription
    description = sdp.SessionDescription.parse(sessionDescription.sdp)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\aiortc\sdp.py", line 385, in parse
    session_lines, media_groups = grouplines(sdp)
                                  ^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\aiortc\sdp.py", line 141, in grouplines
    for line in sdp.splitlines():
                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'

![image](https://github.com/user-attachments/assets/f3f10c58-903d-4a70-a6c0-fc1c70994cfe)

应该是没有启动srs的问题，请问题windows下如何启动srs????????
![image](https://github.com/user-attachments/assets/4015daa3-e6ce-4a04-bd7a-783bd456ef56)

**Comment by tripledoors01** [comment]
请问解决了吗

**Comment by wxzz** [comment]
没解决呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月4日(周日) 中午1:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lipku/metahuman-stream] Error: Cannot connect to host localhost:1985 ssl:default [远程计算机拒绝网络连接。请问windows下如何启动srs??? (Issue #184)




 
请问解决了吗

**Comment by JAVAUVECYM** [comment]
他这个必须要一个外网ip，可以租一个轻量级服务器几十块钱一年的那种在服务器上部署，可以去autodl上看作者的镜像

**Comment by zhaofeng3012** [comment]
> 他这个必须要一个外网ip，可以租一个轻量级服务器几十块钱一年的那种在服务器上部署，可以去autodl上看作者的镜像

是在有公网ip的轻量级服务器上启动srs吗？

**Comment by zhaofeng3012** [comment]
> 没解决呢
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月4日(周日) 中午1:34 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [lipku/metahuman-stream] Error: Cannot connect to host localhost:1985 ssl:default [远程计算机拒绝网络连接。请问windows下如何启动srs??? (Issue #184) 请问解决了吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

您好，我看您关闭了issue，是解决了么？能分享一下解决方案么？

**Comment by wxzz** [comment]
github搜一下srs，第一个项目，有完整的程序包，直接运行就行了。我是windows系统。 @zhaofeng3012

**Comment by zhaofeng3012** [comment]
> github搜一下srs，第一个项目，有完整的程序包，直接运行就行了。我是windows系统。 @zhaofeng3012

是在运行本metahuman-stream项目的机器上启动srs么？还是另一台有公网IP的机器上？
