### ISSUE TITLE
问题求助：在AutoDL上start inference后出现连接失败中止问题，无法生成音视频

### ISSUE THREAD

**Issue by xiwwix** [lipku/metahuman-stream#190]
您好！我先尝试了官方镜像，但是没有视频生成，所以尝试了自己clone一份代码并且按要求上传了模型文件

在运行命令python app.py --model musetalk --transport webrtc，并且按照autodl文档设置了端口代理后，提示start inference，访问http://127.0.0.1:8010/webrtcapi.html可以正常出现ui界面，但是勾选Use STUN server并点击start后无反应，控制台提示
Connection state is connecting
Connection state is failed
Connection state is closed

请问这种情况的原因是什么？我可以如何解决？谢谢！

**Comment by xiwwix** [comment]
已解决，按照readme部署srs（用了阿里云）即可，注意开放端口

**Comment by zhaofeng3012** [comment]
> 已解决，按照readme部署srs（用了阿里云）即可，注意开放端口

您好，请问一下，在autoDL上，已经按readme部署了srs，使用默认模型和以下指令：
 python app.py --listenport 6006 --transport rtcpush --push_url 'http://<阿里云公网ip>:1985/rtc/v1/whip/?app=live&stream=livestream'
，按照autodl文档，打开http://***/rtcpushapi.html，那个奥巴马示例可以跑通。

但使用musetalk模型，您的启动指令是什么呢？是下面这样吗？
python app.py --model musetalk --listenport 6006 --transport rtcpush --push_url 'http://<阿里云公网ip>:1985/rtc/v1/whip/?app=live&stream=livestream'

而且我看作者写的使用musetalk模型的话，打开的是http://***/webrtcapi.html，您使用musetalk后打开的是  http://***/rtcpushapi.html  还是  http://***/webrtcapi.html？
