### ISSUE TITLE
wav2lip  制作自定义形象过程阻塞

### ISSUE THREAD

**Issue by GOOD-N-LCM** [lipku/metahuman-stream#199]
运行 python genavatar.py --video_path xxx.mp4 命令后   全身的图片制作完毕 ，  最后阻塞
![image](https://github.com/user-attachments/assets/87e65ede-7848-433c-8176-09d93c009248)
![image](https://github.com/user-attachments/assets/448255ee-769e-42f0-9313-7a40da3b21c7)
请大佬们  看看是什么原因

**Comment by GOOD-N-LCM** [comment]
predictions.extend(detector.get_detections_for_batch(np.array(images[i:i + batch_size])))
是genavator.py文件里面的face_detect方法，执行阻塞。

**Comment by GOOD-N-LCM** [comment]
没事了  破案了    纯纯显卡算力不够

**Comment by wilsonlv** [comment]
我也卡住了，8g显卡算不动吗
