### ISSUE TITLE
克隆人像和声音，metahuman与GPT-SoVITS接口打通，过程汇总。

### ISSUE THREAD

**Issue by wxzz** [lipku/metahuman-stream#210]
1.启动GPT-SoVITS接口，加载提前克隆好自己的语音模型，训练模型参见： 
  https://blog.csdn.net/m0_59139710/article/details/136371311
  启动命令：
  python api.py -s SoVITS_weights_v2\myself_sound_20240812_e8_s104.pth -g GPT_weights_v2\myself_sound_20240812-e15.ckpt

  打开浏览器，测试接口：
  http://127.0.0.1:9880?refer_wav_path=zh.wav&prompt_text=太祖是怎么评价秦朝宰相李斯的&prompt_language=zh&text=先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也&text_language=zh

  注：text文本不能太短，否则返回的是refer_wav_path的内容。

2.修改metahuman请求GPT-SoVITS接口的代码，打开：ttsreal.py，代码：126行~148行，主要修改req请求参数和res请求地址，代码如下：
  req={
            'refer_wav_path':reffile,
            'prompt_text':reftext,
            'prompt_language':language,
            'text':text,
            'text_language':language
            #'media_type':'raw',
            #'streaming_mode':True
        }
        # req["text"] = text
        # req["text_language"] = language
        # req["character"] = character
        # req["emotion"] = emotion
        # #req["stream_chunk_size"] = stream_chunk_size  # you can reduce it to get faster response, but degrade quality
        # req["streaming_mode"] = True
        res = requests.post(
            f"{server_url}/",
            json=req,
            stream=True,
        )

3.启动SRS,github:https://github.com/ossrs/srs,windows有完整的程序包，端口保持不变。

4.启动metahuman：
  python app.py --transport webrtc --model wav2lip --avatar_id wav2lip_avatar1 --tts gpt-sovits --TTS_SERVER http://127.0.0.1:9880 --REF_FILE zh.wav --REF_TEXT 太祖是怎么评价秦朝宰相李斯的

5.使用wav2lip训练克隆自己人像，参见：readme.txt。
  cd wav2lip
  python genavatar.py --video_path xxx.mp4
  运行后将results/avatars下文件拷到本项目的data/avatars下

注：自己的电脑资源不高的话，如果裁剪出来的图像分辨率太大，那么可以改变图像的分辨率，保留少一些图像，修改genavatar.py代码，自己训练图像模型。

**Comment by zha0jf** [comment]
按上述方式修改后，支持音频流式传输吗？
我的环境里不支持流式传输。如果给GPT-SoVITS的python api.py加上 -sm normal参数，结果依然不支持流式传输，同时音频全变成了噪音。

**Comment by SanBingYouYong** [comment]
如果不适用fast_inference_分支, streaming_mode得是'normal'而不是一个boolean

**Comment by zha0jf** [comment]
> 按上述方式修改后，支持音频流式传输吗？ 我的环境里不支持流式传输。如果给GPT-SoVITS的python api.py加上 -sm normal参数，结果依然不支持流式传输，同时音频全变成了噪音。

此问题的原因是：metahuman-stream对流式音频的要求是raw格式，而GPT-SoVITS master分支的 api.py的流式音频输出格式为 ogg格式，不支持raw格式，导致metahuman-stream接收到之后，不能正确解析流式音频。

目前解决办法是修改 GPT-SoVITS master分支的 api.py 文件，在流式输出中添加对raw输出格式的支持。只需要改几行代码即可。

**Comment by JiaoYuJiaoYu** [comment]
> > 按上述方式修改后，支持音频流式传输吗？ 我的环境里不支持流式传输。如果给GPT-SoVITS的python api.py加上 -sm normal参数，结果依然不支持流式传输，同时音频全变成了噪音。
> 
> 此问题的原因是：metahuman-stream对流式音频的要求是raw格式，而GPT-SoVITS master分支的 api.py的流式音频输出格式为 ogg格式，不支持raw格式，导致metahuman-stream接收到之后，不能正确解析流式音频。
> 
> 目前解决办法是修改 GPT-SoVITS master分支的 api.py 文件，在流式输出中添加对raw输出格式的支持。只需要改几行代码即可。

修改哪几行呀  接入GPT-SoVITS master分支之后延迟高嘛
