### ISSUE TITLE
音频错误问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [lipku/metahuman-stream#218]
您好，我在多次快速输入同一个问题的时，打断机制崩溃报错，显示：File "/home/.conda/envs/nerfstream/lib/python3.8/site-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening <_io.BytesIO object at 0x7f62369f4f90>: Format not recognised，请问如何解决呢？

**Comment by lipku** [comment]
这个问题是自己修正了吗，什么原因

**Comment by JACKYLUO1991** [comment]
@lipku 
![image](https://github.com/user-attachments/assets/671cfa8f-ee01-4d98-97c4-b29da5af30f6)
加一个判断解决的！

**Comment by TigerHH6866** [comment]
> @lipku ![image](https://private-user-images.githubusercontent.com/21237742/363395592-671cfa8f-ee01-4d98-97c4-b29da5af30f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzQ0MDIsIm5iZiI6MTcyNTUzNDEwMiwicGF0aCI6Ii8yMTIzNzc0Mi8zNjMzOTU1OTItNjcxY2ZhOGYtZWUwMS00ZDk4LTk3YzQtYjI5ZGE1YWYzMGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDExMDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhM2Y1ZjAxNDA3OTA1YzM5YzE5MGJjMTlmZDU0M2E2ODFmOWUyMGViMDhlNjc4YTQ0YWNlNDBlYTQ2MGY5ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J4xK_EOLYX3Oi7wGGdXRPGNilupL7T9vV_WA0S1Usn8) 加一个判断解决的！

佬，请问加在哪里呢？
我也遇到这个问题
