### ISSUE TITLE
Cannot Start app.py with 'Error: Cannot connect to host localhost:1985' 

### ISSUE THREAD

**Issue by irrikrlla** [lipku/metahuman-stream#228]
![屏幕截图 2024-08-25 111450](https://github.com/user-attachments/assets/45a417c7-4571-45ee-9d04-0f0f2d8aae4f)

After model-loading part when ran app.py, I got an unexpected network error, Error: Cannot connect to host localhost:1985 ssl:default, and aiortc\sdp.py got AttributeError: 'NoneType' object has no attribute 'splitlines'. As the screenshot shows. How could I solve this strange error?

**Comment by lipku** [comment]
run srs first
