### ISSUE TITLE
刷新页面，或者是点击stop按钮再刷新，还会播放上一个页面的流

### ISSUE THREAD

**Issue by KelvinHuang66** [lipku/metahuman-stream#236]
在哪里设置，刷新页面或者是点击stop按钮就立刻终止当前任务，刷新后重新开启服务，我发现刷新或者是stop并不会终止tts跟推流的协程

**Comment by KelvinHuang66** [comment]
在render添加self.pause_talk()解决了该问题，但是切换时偶尔会有杂音

**Comment by Surrin1999** [comment]
杂音问题如何解决呢？
