### ISSUE TITLE
非常棒的数字人！每次运行，都是人嘴巴先动1-2秒钟，然后才有声音

### ISSUE THREAD

**Issue by ThornbirdZhang** [lipku/metahuman-stream#244]
非常感谢，很好的数字人项目！
碰到一个问题，无论是nerfreal，还是musetalk，都会碰到嘴巴先动1-2秒，然后才有声音。仔细看，好像口型与声音也同步。
嘴巴先动是什么原因呢？
在nerfreal.py的test_step中尝试将type=0的音频，以及同时的视频保存下来，发现对的很整齐，没有问题。还请大佬赐教。

**Comment by lipku** [comment]
用的哪种传输方式

**Comment by ThornbirdZhang** [comment]
采用webrtc。nerf、muse都试过，情况类似：推理输出的图片和声音对的误差不超过3帧，但是在客户端上就明显嘴巴先动，而声音后至。附上一个录制视频，麻烦看看。

https://github.com/user-attachments/assets/ee32b37f-82a0-42c9-8ca7-4343d39ca6fa

感觉srs的播放器，在微信等浏览器里面播放会出问题，卡顿，甚至有重复，明天再确认一下。

**Comment by ThornbirdZhang** [comment]
微信中SRS的播放效果很不好，卡顿。

**Comment by ThornbirdZhang** [comment]
webrtc问题已经解决，python的线程互相干扰。

**Comment by lipku** [comment]
修改哪里解决的

**Comment by gg22mm** [comment]
这个怎么设置 保存成视频呀，虽然流输出很棒，但是有时候也想生成视频~~

**Comment by qwert1887** [comment]
@ThornbirdZhang 大佬，webrtc长时间运行嘴巴会延后几秒，有这种情况吗？

**Comment by talentjls** [comment]
> webrtc问题已经解决，python的线程互相干扰。

请问有什么线程干扰问题呢，我也遇到相同的问题

**Comment by wenjunyan00** [comment]
> webrtc问题已经解决，python的线程互相干扰。

这个问题如何解决，大佬能否给个方案

**Comment by tangping-cmd** [comment]
这个问题如何解决，大佬能否给个方案
