### ISSUE TITLE
大佬，tts用gpt-sovits时，人物说话有一顿一顿的杂音？在gpt-sovits上或者直接接口调用tts都没有这种情况。

### ISSUE THREAD

**Issue by Proletariat-wh** [lipku/metahuman-stream#259]

**Comment by Wcy0802** [comment]
请问下，语音会卡顿这个问题解决了嘛

**Comment by yehx1** [comment]
您好，请问这个杂音的问题解决了吗

**Comment by Proletariat-wh** [comment]
时间太久，我记得是调整采样频率sample_rate，在原有基础乘2




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lipku/LiveTalking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月31日(星期二) 中午11:47
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [lipku/LiveTalking] 大佬，tts用gpt-sovits时，人物说话有一顿一顿的杂音？在gpt-sovits上或者直接接口调用tts都没有这种情况。 (Issue #259)





 
您好，请问这个杂音的问题解决了吗

**Comment by Proletariat-wh** [comment]
时间太久，我记得是调整采样频率sample_rate，在原有基础乘2







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lipku/LiveTalking"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月5日(星期四) 中午11:21
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [lipku/LiveTalking] 大佬，tts用gpt-sovits时，人物说话有一顿一顿的杂音？在gpt-sovits上或者直接接口调用tts都没有这种情况。 (Issue #259)





 
请问下，语音会卡顿这个问题解决了嘛
