### ISSUE TITLE
推流语速问题

### ISSUE THREAD

**Issue by lswc225** [lipku/metahuman-stream#28]
使用现有奥巴马模型,现有语音模型,跑起来推流的时候,发现语速很快,有没有控制参数可用?使用 rtmp_streaming 有参数可以控制吗?

**Comment by lipku** [comment]
打印的fps是多少

**Comment by lswc225** [comment]
> 打印的fps是多少

fps我们没有目前还是按照源码里面的配置推流的,没有做改动

**Comment by lswc225** [comment]
> > 打印的fps是多少
> 
> fps我们没有目前还是按照源码里面的配置推流的,没有做改动

-actual avg fps:43.9754 这个是运行起来之后打印的fps值

**Comment by lipku** [comment]
render函数里打开这里
# delay = 0.04 - (time.time() - t) #40ms
  # if delay > 0:
    #     time.sleep(delay)

**Comment by lswc225** [comment]
感谢感谢,语速问题解决了

**Comment by BO-DI** [comment]
> 感谢感谢,语速问题解决了

请问，我用的时默认的Edge_TTS,数字人说话一卡一卡的是怎么回事呢？
