### ISSUE TITLE
srs镜像从哪儿获取呢？

### ISSUE THREAD

**Issue by westernbuptboy** [lipku/metahuman-stream#3]
作者您好，按照readme基本已经完成了所有的配置，但是这一步  docker run --rm -it -p 1935:1935 -p 1985:1985 -p 8080:8080 registry.cn-hangzhou.aliyuncs.com/ossrs/srs:5 中的镜像是从哪儿下载呢？还是说这些操作只能在阿里云服务器上执行？谢谢

**Comment by lipku** [comment]
直接执行这个命令就会自动下载了

**Comment by westernbuptboy** [comment]
> 直接执行这个命令就会自动下载了

谢谢，已经可以了。
再请教一下，执行python app.py  一直会提示这个，可能是什么原因呢？
  File "/data/code/metahuman-stream/raymarching/raymarching.py", line 10, in <module>
    import _raymarching_face as _backend
ModuleNotFoundError: No module named '_raymarching_face'
