### ISSUE TITLE
求助运行python app.py出现如下错误

### ISSUE THREAD

**Issue by azraeljian** [lipku/metahuman-stream#36]
求助ubuntu下运行python app.py出现如下错误，docker 正常运行srs
![1111111111111111112222222222222](https://github.com/lipku/metahuman-stream/assets/16833943/57a1006d-8b1d-4627-876d-fa472a9a3c56)
电脑没有声卡没事把

**Comment by azraeljian** [comment]
解决了，是ffmpeg版本问题

**Comment by zhangdanfeng888** [comment]
> 解决了，是ffmpeg版本问题

请问装了ffmpeg哪个版本呢？
