### ISSUE TITLE
运行python app.py报错

### ISSUE THREAD

**Issue by zhangdanfeng888** [lipku/metahuman-stream#48]
![image](https://github.com/lipku/metahuman-stream/assets/41187774/69266c5f-ab44-4abd-95c8-b109396c70a2)
后续可以执行，但是内容一直加载不出来
![image](https://github.com/lipku/metahuman-stream/assets/41187774/da7c8ac1-f369-4984-8d18-a54930d6f720)

**Comment by zhangdanfeng888** [comment]
docker后台也报错：
![image](https://github.com/lipku/metahuman-stream/assets/41187774/b9f64cd1-b96b-4af2-bbaf-b4a0e039c848)
是python_rtmpstream这个项目没配置好吗？

**Comment by huyppppppp** [comment]
> docker后台也报错： ![image](https://private-user-images.githubusercontent.com/41187774/317250519-b9f64cd1-b96b-4af2-bbaf-b4a0e039c848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTAxNzksIm5iZiI6MTcxMTU4OTg3OSwicGF0aCI6Ii80MTE4Nzc3NC8zMTcyNTA1MTktYjlmNjRjZDEtYjk2Yi00YWYyLWJiYWYtYjRhMGUwMzljODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAxMzc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NzgwM2QxODcxMjRiMTBmYzhjMTUwNjhiYWZmODNmODAzM2FjMTRmYmI4MzQxZGQ2MGNjNTI1MTljNmFhYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2hpumcDWrb_B_KZ2Ffm_t4T2xhlT7WaOcqpA7AcUTY) 是python_rtmpstream这个项目没配置好吗？

我也是一样的错误，请问解决了吗

**Comment by zhangdanfeng888** [comment]
> > docker后台也报错： ![image](https://private-user-images.githubusercontent.com/41187774/317250519-b9f64cd1-b96b-4af2-bbaf-b4a0e039c848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTAxNzksIm5iZiI6MTcxMTU4OTg3OSwicGF0aCI6Ii80MTE4Nzc3NC8zMTcyNTA1MTktYjlmNjRjZDEtYjk2Yi00YWYyLWJiYWYtYjRhMGUwMzljODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAxMzc1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3NzgwM2QxODcxMjRiMTBmYzhjMTUwNjhiYWZmODNmODAzM2FjMTRmYmI4MzQxZGQ2MGNjNTI1MTljNmFhYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t2hpumcDWrb_B_KZ2Ffm_t4T2xhlT7WaOcqpA7AcUTY) 是python_rtmpstream这个项目没配置好吗？
> 
> 我也是一样的错误，请问解决了吗

没有唉，不知道怎么搞

**Comment by zhangdanfeng888** [comment]
在windows系统上搞定了

**Comment by gt2ming** [comment]
> 在windows系统上搞定了

请问是在windows11上用wsl吗？还是直接用命令行执行docker呢？

**Comment by zhangdanfeng888** [comment]
> > 在windows系统上搞定了
> 
> 请问是在windows11上用wsl吗？还是直接用命令行执行docker呢？

我是直接在Win10系统上配置的环境，安装rtmp的时候改了好几个地方，折腾了很久
