### ISSUE TITLE
全身视频贴图后，切割线处对应不上

### ISSUE THREAD

**Issue by redstarxz** [lipku/metahuman-stream#49]
https://github.com/lipku/metahuman-stream/assets/1501291/aa2f8733-bedc-48bf-9b05-1b501814662a

那个领带处切割感很明显。用的是最新代码。

**Comment by lipku** [comment]
readme里有说明，加torso_img参数

**Comment by Tiandishihua** [comment]
> 694_1711808558.mp4 
> 那个领带处切割感很明显。用的是最新代码。

我也是，请问你解决了吗

**Comment by pihang** [comment]
> 694_1711808558.mp4 
> 那个领带处切割感很明显。用的是最新代码。

请问训练er-nerf是切割后的头部去训练吗，为啥我拼接后不仅切割感明显而且头部模型推理出来的感觉放大了，有种大头特效

**Comment by Jacoo-ai** [comment]
> readme里有说明，加torso_img参数

大佬你好，如果加了这个参数还是有切割线，应该怎么处理呢？

**Comment by brightlin6** [comment]
我遇上了同样的问题， torso_img 加上也是一样   明显的头部和身体分离
