### ISSUE TITLE
SRS镜像

### ISSUE THREAD

**Issue by huyppppppp** [lipku/metahuman-stream#50]
请问使用更快地SRS需要更改echo.html吗，我用第一个SRS可以有画面，第二个更快地没有画面出现

**Comment by lipku** [comment]
不需要更改

**Comment by huyppppppp** [comment]
> 不需要更改

运行第二个会出现这个错误
<img width="572" alt="error" src="https://github.com/lipku/metahuman-stream/assets/116953013/12e1a917-4ebc-4772-99d4-3b0ed3c1417a">
请问是什么原因呀？

**Comment by huyppppppp** [comment]
> 不需要更改
大佬我还有一个问题，为什么我刚开服务的时候延迟大概五秒，长时间不用后再次使用延时变成了十几秒，这是什么原因呀
