### ISSUE TITLE
搭建完成，在网页调用tts合成的时候报错

### ISSUE THREAD

**Issue by westernbuptboy** [lipku/metahuman-stream#6]
请教作者，这个可能是什么原因？谢谢
![image](https://github.com/lipku/metahuman-stream/assets/41902297/fc156216-6d29-4376-a9ff-f3a935f0dd3f)
![image](https://github.com/lipku/metahuman-stream/assets/41902297/4c0330fe-9b4d-461a-b916-817dfc7b80ac)

**Comment by lipku** [comment]
更新了一下代码，你再试一下看看
