### ISSUE TITLE
webrtc

### ISSUE THREAD

**Issue by huyppppppp** [lipku/metahuman-stream#62]
使用webrtc，不能显示视频，请问是什么原因呀
![屏幕截图 2024-04-19 113800](https://github.com/lipku/metahuman-stream/assets/116953013/a4c89573-1536-4713-aaba-90b76b19c051)
服务器端是这样的
![屏幕截图 2024-04-19 113918](https://github.com/lipku/metahuman-stream/assets/116953013/59d6f076-0dec-46c8-a928-8b7259b89de4)
![屏幕截图 2024-04-19 113944](https://github.com/lipku/metahuman-stream/assets/116953013/6ff9bfbb-a669-4a58-bc95-6896fb7c642d)

**Comment by lipku** [comment]
把服务端udp端口50000--60000放开， 还不行就把udp端口都放开试一下

**Comment by huyppppppp** [comment]
> 把服务端udp端口50000--60000放开， 还不行就把udp端口都放开试一下

好的感谢

**Comment by yimikai** [comment]
> > 把服务端udp端口50000--60000放开， 还不行就把udp端口都放开试一下
> 
> 好的感谢

好了么？
