### ISSUE TITLE
webrtc得到的视频声音有很明显的电流声

### ISSUE THREAD

**Issue by zhangdanfeng888** [lipku/metahuman-stream#63]
如题，用edgetts和gpt-sovits都是这样，请问怎么是回事呢？

**Comment by superwhys** [comment]
+1

**Comment by noodles-dumplings** [comment]
+1，尝试了Chrome、Edge、Firefox音质都不行，直接调用gpt-sovits的tts接口返回结果的音质正常。
尝试修改offer sdp的maxaveragebitrate和maxplaybackrate没生效。
尝试修改webrtc.py中的采样率没生效。

**Comment by he1chenglong** [comment]
+1

**Comment by lipku** [comment]
最新代码解决了该问题
