### ISSUE TITLE
在替换自己模型的时候报参数不一致错误，应该怎么修改或者去哪里修改

### ISSUE THREAD

**Issue by zangruoxiang1** [lipku/metahuman-stream#76]
[INFO] Trainer: ngp | 2024-05-07_08-43-54 | cuda | fp16 | data/video
[INFO] #parameters: 1789121
[INFO] Loading data/pretrained/ngp_kf.pth ...
Traceback (most recent call last):
  File "D:\metahuman-stream-main\app.py", line 442, in <module>
    trainer = Trainer('ngp', opt, model, device=device, workspace=opt.workspace, criterion=criterion, fp16=opt.fp16, metrics=metrics, use_checkpoint=opt.ckpt)
  File "D:\metahuman-stream-main\nerf_triplane\utils.py", line 705, in __init__
    self.load_checkpoint(self.use_checkpoint)
  File "D:\metahuman-stream-main\nerf_triplane\utils.py", line 1471, in load_checkpoint
    missing_keys, unexpected_keys = self.model.load_state_dict(checkpoint_dict['model'], strict=False)
  File "C:\ProgramData\anaconda3\envs\nerfstream\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
        size mismatch for audio_net.encoder_conv.0.weight: copying a param with shape torch.Size([32, 29, 3]) from checkpoint, the shape in current model is torch.Size([32, 44, 3]).

        是什么原因导致的，应该去哪里修改这个参数

**Comment by zangruoxiang1** [comment]
弄明白了，训练模型应该使用wav2来训练

**Comment by lipku** [comment]
预处理数据时要用wav2vec

**Comment by jackw10002** [comment]
> 弄明白了，训练模型应该使用wav2来训练

你好，我想问一下用wav2vce预处理的数据后，在音频和视频报出
<img width="946" alt="屏幕截图 2024-07-04 111754" src="https://github.com/lipku/metahuman-stream/assets/135308038/7cff4c4b-aa1a-4474-b523-7fe1ad9b287f">，请问你在后期训练的时候有遇到嘛？

**Comment by lucian196** [comment]
> 你好，可以具体说说如何使用wav2来训练吗，我在训练命令中加入了--asr_model esperanto，结果训练这边也报出了类似的错误ww

你好，请问后面拟解决了吗？

**Comment by lipku** [comment]
看faq

**Comment by wRinnori** [comment]
感谢，已经解决了

**Comment by zzbcola** [comment]
> 感谢，已经解决了

您好，请问可以说说具体怎么解决吗？我也遇到了同样的问题。

**Comment by LEONPICKBOY** [comment]
训练模型时加入 --asr_model cpierse/wav2vec2-large-xlsr-53-esperanto   
如果训练模型时也报这个错，就先删除训练好的模型，重新训练

**Comment by zzbcola** [comment]
问题已解决，感谢您的回答。
________________________________
发件人: LEONPICKBOY ***@***.***>
发送时间: 2024年12月20日 11:36
收件人: lipku/LiveTalking ***@***.***>
抄送: zhouzhibiao ***@***.***>; Comment ***@***.***>
主题: Re: [lipku/LiveTalking] 在替换自己模型的时候报参数不一致错误，应该怎么修改或者去哪里修改 (Issue #76)


训练模型时加入 --asr_model cpierse/wav2vec2-large-xlsr-53-esperanto
如果训练模型时也报这个错，就先删除训练好的模型，重新训练

―
