### ISSUE TITLE
[aac @ 0x953bb00] Input contains (near) NaN/+-Inf

### ISSUE THREAD

**Issue by lzzbutphh** [lipku/metahuman-stream#9]
我们完成了搭建，但是出现了这个错误，貌似是音频解码的错误。
这个错误是随机的，有些音频可以推送，但是推送失败的音频在本地可以整成播放。
请问作者知道这样的原因吗？

**Comment by lzzbutphh** [comment]
实在执行 ffmpeg 解码的时候发生的错误

**Comment by lipku** [comment]
这个不影响使用。是因为最后一个音频包不是20ms长度，可以不发那个包
